const GAME_CONFIG = {
  ROUNDS: 6,
  TIME_PER_QUESTION: 10,
  BASE_POINTS: 20,
  MIN_POINTS: 5,
  BONUS_MULTIPLIER: 2,
  INTRO_MS: 1600,
};

const ROOM_TTL_MS = 10 * 60 * 1000;
const CODE_ALPHABET = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';

module.exports = { GAME_CONFIG, ROOM_TTL_MS, CODE_ALPHABET };
