const commonsFile = (name) =>
  `https://commons.wikimedia.org/wiki/Special:Redirect/file/${encodeURIComponent(name)}?width=960`;

const commonsPage = (name) =>
  `https://commons.wikimedia.org/wiki/File:${encodeURIComponent(name)}`;

const cover = (file, focal = 'center 35%') => ({
  src: commonsFile(file),
  source: commonsPage(file),
  focal,
});

export const FAMILY_TOPIC_COVERS = {
  entertainment: cover('Debrie Parvo 35mm Movie Camera.jpg', 'center 48%'),
  music: cover('BBC Proms 31.jpg', 'center 46%'),
  sport: cover('4 sports photo.jpg', 'center 42%'),
  culture: cover('OrteliusWorldMap.jpeg', 'center 42%'),
  gaming: cover('ArcadeGames.jpg', 'center 45%'),
};

// Every entry is reviewed for immediate topic recognition at thumbnail size.
// Unreviewed categories intentionally keep their graphic tile instead of
// receiving a misleading generic family photograph.
export const TOPIC_COVERS = {
  movies: cover('Debrie Parvo 35mm Movie Camera.jpg', 'center 48%'),
  music: cover('BBC Proms 31.jpg', 'center 46%'),
  sports: cover('4 sports photo.jpg', 'center 42%'),
  geography: cover('OrteliusWorldMap.jpeg', 'center 42%'),
  gaming: cover('ArcadeGames.jpg', 'center 45%'),
  science: cover('Laboratory.jpg', 'center 38%'),
  rap_fr: cover("IAM à l'Olympia de Montréal.jpg", 'center 30%'),
  foot_fr: cover('Kylian Mbappe - France v Norway - 26 June 2026 (cropped).jpg', 'center 24%'),
  cinema_fr: cover('Famous French Actors.jpg', 'center 32%'),
  culture_fr: cover('Mont Saint-Michel France.jpg', 'center 42%'),
  premier_league: cover('Interior of Hill Dickinson Stadium.jpg', 'center 42%'),
  la_liga: cover('Lamine Yamal France v Spain 7.24.26-187.jpg', 'center 24%'),
  ligue_1: cover('PSG - Lille Ligue 1.jpg', 'center 42%'),
  netflix: cover('100 Winchester Circle.jpg', 'center 42%'),
  seconde_guerre_mondiale: cover('WW2Montage.PNG', 'center 42%'),
  fortnite: cover('Fortnite cosplay at E3 2018.jpg', 'center 25%'),
  lionel_messi: cover('Lionel Messi WC2022.jpg', 'center 22%'),
  bandes_originales_de_films: cover('Prague recording session, June 2004.jpg', 'center 42%'),
  culture_manga: cover('Japan Bookstore.jpg', 'center 42%'),
  films_pixar: cover('Pixaranimationstudios.jpg', 'center 42%'),
  mythologie_grecque: cover('Zeus Otricoli Pio-Clementino Inv257.jpg', 'center 25%'),
  mythologie_egyptienne: cover('Egypt Abou Simbel3.jpg', 'center 42%'),
  films_musicaux: cover('Gentlemen Prefer Blondes Movie Trailer Screenshot (34).jpg', 'center 25%'),
  legendes_de_l_esport: cover('Caps 2025.jpg', 'center 24%'),
  cyclisme_stars: cover('Vélo de route.jpg', 'center 42%'),
  got: cover('Iron Throne Moscow Metro (2019-05-11) 01 (cropped).jpg', 'center 38%'),
  harry_potter: cover('Wizarding World of Harry Potter Castle.jpg', 'center 44%'),
  marvel: cover('Cosplay of Tony Stark, Captain America and Iron Man at LBCC 2013 (edited homogeneous background).jpg', 'center 28%'),
  star_wars: cover('NYCC 2023 Cosplay of Darth Vader.jpg', 'center 24%'),
  disney: cover('SleepingBeautyCastle.JPG', 'center 42%'),
  pokemon: cover('Pikachu Parade (14905092432).jpg', 'center 34%'),
  f1: cover('Lewis Hamilton during Hungarian Formula 1 GP.jpg', 'center 24%'),
  nba: cover('LeBron James (31944491583).jpg', 'center 28%'),
  tv_shows: cover('Central Perk set.jpg', 'center 46%'),
  histoire_fr: cover('Eugène Delacroix - La liberté guidant le peuple - après restauration 2024.jpg', 'center 36%'),
  retro_games: cover('NES-Console-Set.jpg', 'center 48%'),
  espace_astronomie: cover('Pillars of Creation.jpeg', 'center 42%'),
  corps_humain: cover('Human Anatomy (NIH BioArt 519 - 657946).png', 'center 42%'),
  ligue_champions: cover('Champions League Trophy (52736201132).jpg', 'center 38%'),
  coupe_du_monde_histoire: cover('Kylian Mbappé World Cup Trophy.jpg', 'center 25%'),
  tour_de_france: cover('UAE Team, Tadej Pogačar - Yellow jersey peloton with crowd in Peyresourdes during stage 14 of Tour de France 2025 (cropped).jpg', 'center 30%'),
  jo_ete_histoire: cover('Olympic rings on the Eiffel Tower 2024 (11).jpg', 'center 43%'),
  can_foot_africain: cover('Trophée CAN (1).jpg', 'center 38%'),
  copa_america: cover('Copa america trofeo.jpg', 'center 38%'),
  legendes_foot_allemand_anglais_italien: cover('Cristiano Ronaldo 2018 (4x5 cropped).jpg', 'center 24%'),
  eredivisie: cover('Eredivisie Trophy.png', 'center 42%'),
  drapeaux: cover('Flag Map of The World (2026).png', 'center 45%'),
  liga_portugal: cover('The 2016-17 Primeira Liga Trophy.jpg', 'center 42%'),
  mls: cover('Lionel Messi NE Revolution Inter Miami 7.9.25-165.jpg', 'center 24%'),
  tennis_atp: cover('Carlos Alcaraz Argentina Open 2024.jpg', 'center 24%'),
  tennis_wta: cover('Iga Swiatek 2023 (cropped).jpg', 'center 24%'),
  roland_garros: cover('Rafael Nadal Roland Garros.jpg', 'center 26%'),
  wimbledon: cover('Wimbledon Centre Court (52205402762).jpg', 'center 42%'),
  rugby_top_14: cover('ST vs RCT 2012 12 Thierry Dusautoir 2.jpg', 'center 28%'),
  mma_ufc: cover('Conor McGregor 2015.jpg', 'center 24%'),
  legendes_du_cyclisme: cover('Eddy Merckx-1973.jpg', 'center 26%'),
  natation_olympique: cover('Michael Phelps conquista 20ª medalha de ouro e é ovacionado 1036417-09082016- mg 6661 01.jpg', 'center 28%'),
  jo_d_hiver_histoire: cover('Cortina d’Ampezzo Olympic Rings 2025 - XXV Giochi olimpici invernali.jpg', 'center 42%'),
  volleyball: cover('Brasil vence a França no vôlei masculino 1037983-15.08.2016 ffz-5559.jpg', 'center 30%'),
  ski_alpin: cover('Lindsey Vonn in Courchevel, 20 december 2015 09.JPG', 'center 25%'),
  sports_d_hiver: cover('Martin Fourcade au tir lors des Jeux Mondiaux Militaires 2013.JPG', 'center 30%'),
  golf: cover('Tiger Woods 20180927.jpg', 'center 25%'),
  nhl: cover('Wgretz edit2.jpg', 'center 25%'),
  baseball_mlb: cover('Shohei Ohtani on April 23, 2024 (2) 53677192000.jpg', 'center 24%'),
  motogp: cover('Valentino Rossi (15131915515).jpg', 'center 25%'),
  rallye_wrc: cover('Sébastien Loeb - 2007 Rally Portugal.jpg', 'center 34%'),
  paris_saint_germain: cover('PSG champion 2015.jpg', 'center 35%'),
  real_madrid: cover('Real Madrid celebration after winning the 2018 UEFA Champions League Final DSC 0459 (40596061330).jpg', 'center 34%'),
  cristiano_ronaldo: cover('2019-20 Serie A - Torino v Juventus - Cristiano Ronaldo (cropped).jpg', 'center 23%'),
  minecraft: cover('Gamescom 2025 Minecraft.jpg', 'center 38%'),
  gta: cover('Grand-Theft-Auto.png', 'center 45%'),
  league_of_legends: cover('Faker at Worlds 2024.jpg', 'center 24%'),
  valorant: cover('Valorant Champions Tour logo.png', 'center 50%'),
  roblox: cover('Roblox Logo.svg', 'center 50%'),
  call_of_duty: cover('Captain Price cosplay.jpg', 'center 24%'),
  genshin_impact: cover('Cosplay of Raiden Shogun at Made in Asia 2022 (52106490344).jpg', 'center 24%'),
  zelda: cover('Link et Zelda Cosplay.jpg', 'center 25%'),
  univers_mario: cover('Mario and Luigi.jpg', 'center 28%'),
  rugby_coupe_du_monde: cover('RWC 2011 final FRA - NZL McCaw with Ellis Cup.jpg', 'center 30%'),
  xv_de_france: cover('Antoine Dupont February 2023.jpg', 'center 24%'),
  boxe_champions: cover('Muhammad Ali fights Brian London on August 6, 1966 (cropped).jpg', 'center 32%'),
  handball: cover('Nikola Karabatic Team France Handball World Championship 2019 IHF (32931666457).jpg', 'center 27%'),
  nfl: cover('Tom Brady Super Bowl LII 85F9D5D.jpg', 'center 24%'),
  gymnastique: cover('Simone biles 2024 Olympics.jpg', 'center 25%'),
  patinage_artistique: cover('2019 Skate Canada International - Yuzuru Hanyu FS.jpg', 'center 27%'),
  sports_extremes: cover("Tony Hawk skating the Ann Arbor skatepark at Veteran's Memorial Park (cropped).jpg", 'center 35%'),
  femmes_du_sport: cover('SERENA WILLIAMS (3247978825).jpg', 'center 24%'),
  jeunes_talents_du_sport: cover('Lamine Yamal in 2025 (cropped).jpg', 'center 24%'),
  legendes_du_sport_francais: cover('Zinedine zidane wcf 2006.jpg', 'center 25%'),
  padel: cover('Vigo Open 2019 de World Padel Tour - 38.jpg', 'center 36%'),
  beach_volley: cover('Woman beach volley at Paris 2024 olympics France vs Germany 28 07 2024 group stage (cropped).jpg', 'center 32%'),
  k_pop_groupes_feminins: cover('Blackpink Pink Carpet Event 1.jpg', 'center 27%'),
  k_pop_groupes_masculins: cover('190115 BTS at the 2019 Seoul Music Awards.jpg', 'center 28%'),
  bts: cover('BTS in concert at Wembley Stadium, 2 June 2019 01.jpg', 'center 32%'),
  blackpink: cover('Blackpink Pink Carpet Event 3.jpg', 'center 26%'),
  afrobeats: cover('Untold 2024 -Burna Boy (53926047977) (cropped).jpg', 'center 24%'),
  latin_pop_reggaeton: cover('Bad Bunny Performs.jpg', 'center 24%'),
  rap_us_legendes: cover('Eminem performing in 2014 (cropped).jpg', 'center 24%'),
  r_b: cover('Beyonce, I Am... Tour, Bercy 2009.jpg', 'center 24%'),
  variete_francaise: cover('Jean-Jacques Goldman - may 2002.jpg', 'center 25%'),
  chanson_francaise_classique: cover('Edith Piaf Harcourt 1950 2.jpg', 'center 25%'),
  rock_francais: cover('Concert Indochine Arena Tour LDLC Arena - Décines-Charpieu (FR69) - 2025-02-07 - 79.jpg', 'center 28%'),
  rock_legendes_anglo_us: cover('FreddieMercuryNov1977.jpg', 'center 24%'),
  metal: cover('Metallica Warsaw 2024.jpg', 'center 34%'),
  pop_rock_2000s: cover('Avril Lavigne Stage Greatest Hits Tour 2025.jpg', 'center 25%'),
  electro_edm: cover('David Guetta DJing at Ushuaïa Ibiza 2023-07-03 hq.jpg', 'center 25%'),
  house_techno: cover('Daft Punk, 14-6-2007, Bercy, Paris.jpg', 'center 38%'),
  reggae_dancehall: cover('Bob-Marley.jpg', 'center 24%'),
  jazz_legendes: cover('Miles Davis Strasbourg profil bis.jpg', 'center 25%'),
  compositeurs_classiques: cover('Beethoven.jpg', 'center 24%'),
  eurovision: cover('Eurovision 2024 winner Nemo with trophy.jpg', 'center 27%'),
  festivals_de_musique: cover('Coachella main stage at sunset 2004.jpg', 'center 44%'),
  clips_iconiques: cover('Michael Jackson in 1988 (cropped).jpg', 'center 23%'),
  duos_collabs_celebres: cover('Beyoncé and Jay-Z On The Run II.jpg', 'center 29%'),
  comedies_musicales: cover('Stage of the Walter Kerr Theatre with the set of Hadestown.jpg', 'center 45%'),
  girl_groups_boys_bands_2000s_2010s: cover('Spice Girls.jpg', 'center 30%'),
  musique_annees_80: cover('Madonna in concert wearing fishnets 1987 (cropped).jpg', 'center 25%'),
  anime_shonen: cover('Group Portrait of Naruto Cosplayers at CWT40 20150809.jpg', 'center 28%'),
  studio_ghibli: cover('Ghibli Museum - Totoro.jpg', 'center 34%'),
  anime_cultes: cover('Group Portrait of Sailor Moon Cosplayers at CWT41 20151212.jpg', 'center 28%'),
  dc_comics: cover('Cosplay of Batman and Superman at Brussels Comic Con 2022 (51985492234).jpg', 'center 28%'),
  films_dreamworks: cover('Shrek & Fiona.jpg', 'center 26%'),
  comedies_francaises: cover('Louis de Funès 1970.jpg', 'center 24%'),
  comedies_us_cultes: cover('Montreal Comiccon 2016 - The Mask (27999721470).jpg', 'center 24%'),
  films_d_horreur: cover('Fan Expo 2015 - Freddy Krueger & Jason Voorhees (21146338493).jpg', 'center 27%'),
  science_fiction: cover("Astronaut, cosmonaut space suit model in Kennedy Space Center Visitor Complex.jpg", 'center 31%'),
  films_cultes_90s: cover("Costumes du film Titanic.jpg", 'center 36%'),
  films_cultes_2000s: cover("Daniel Radcliffe as Harry Potter.jpg", 'center 24%'),
  oscars_histoire: cover("Ingrid Bergman Holding Oscar.jpg", 'center 27%'),
  cesars: cover("Quentin Tarantino Césars 2011.jpg", 'center 25%'),
  k_pop_rookies_2025_26: cover("Babymonster at Incheon Airport.jpg", 'center 29%'),
  pop_us_montante: cover("Sabrina Carpenter - O2 Arena 2025 - 070 (cropped).jpg", 'center 24%'),
  chappell_roan_pop_alternative: cover("Chappell Roan Sziget 2025.jpg", 'center 25%'),
  rap_us_nouvelle_generation: cover("Travis Scott Circus Maximus Tour Orlando, FL.jpg", 'center 30%'),
  drill_fr_uk: cover("Central cee-5.jpg", 'center 24%'),
  musique_annees_90: cover("Britney Spears 1999.jpg", 'center 25%'),
  musique_annees_2010: cover("Taylor Swift The Eras Tour 1989 Era Set (53109939870) (cropped).jpg", 'center 28%'),
  sons_viraux_tiktok: cover("Charli D'Amelio.jpg", 'center 24%'),
  rappeuses_francaises: cover("Aya Nakamura IMG 4756 (cropped).jpg", 'center 24%'),
  nouvelle_scene_rap_fr: cover("TiakolaConcert.jpg", 'center 27%'),
  wednesday: cover("Jenna Ortega and Catherine Zeta-Jones 2025 promoting Wednesday.jpg", 'center 26%'),
  stranger_things: cover("Stranger Things cast by Gage Skidmore.jpg", 'center 27%'),
  euphoria: cover("Zendaya 2024 (cropped).jpg", 'center 24%'),
  heartbreak_high: cover("Ayesha Madon for Maybelline Australia & New Zealand 02.jpg", 'center 24%'),
  xo_kitty: cover("Anna Cathcart at WWD Style Awards 2026 (cropped).jpg", 'center 24%'),
  sex_education: cover("Aimee Lou Wood.jpg", 'center 24%'),
  k_dramas: cover("Crash Landing on You cast.jpg", 'center 28%'),
  squid_game: cover("20210923—Lee Jung-jae 이정재, interview, ELLE Taiwan screenshot (02m06s).jpg", 'center 24%'),
  james_bond: cover("Daniel Craig - James Bond (48707836782) (cropped).jpg", 'center 24%'),
  fast_furious: cover("Fast Five Cast.jpg", 'center 29%'),
  films_de_braquage: cover("Affleck09The Town.jpg", 'center 27%'),
  realisateurs_cultes: cover("Quentin Tarantino 2009.jpg", 'center 24%'),
  acteurs_hollywoodiens_actuels: cover("Timothée Chalamet-63815b.jpg", 'center 24%'),
  actrices_hollywoodiennes_actuelles: cover("Margot Robbie at 29th Critics' Choice Awards.jpg", 'center 24%'),
  stars_du_cinema_coreen: cover("Lee Byung-hun 2025 Toronto (cropped).jpg", 'center 24%'),
  sitcoms_cultes: cover("Friends actors montage.jpg", 'center 33%'),
  tele_realite_fr: cover("Nabilla Benattia 2023 (cropped).jpg", 'center 24%'),
  humoristes_francais: cover("Gad Elmaleh - D'ailleurs.jpg", 'center 26%'),
  stand_up_us: cover("Kevin Hart (15789082350).jpg", 'center 24%'),
  youtubeurs_francais: cover("Squeezie Zack en Roue Libre 2025 (cropped).png", 'center 24%'),
  streamers_twitch_fr: cover("Inoxtag-2023.jpg", 'center 24%'),
  streamers_internationaux: cover("Kai Cenat 2023 (cropped).jpg", 'center 24%'),
  tiktokeurs_celebres: cover("Khaby Lame, Jake from State Farm, and Mat during Tik Tok video shoots (Khaby Lame cropped).jpg", 'center 24%'),
  influenceurs_beaute: cover("James Charles - GLAAD Media Awards 2024 (cropped).png", 'center 24%'),
  createurs_gaming: cover("PewDiePie at PAX 2015.jpg", 'center 24%'),
  celebrites_reseaux_sociaux: cover("MrBeast in 2026 (3x4 cropped).png", 'center 24%'),
  mode_defiles: cover("Paris Fashion Week.jpg", 'center 39%'),
  icones_de_la_mode: cover("Diane von Fürstenberg Spring-Summer 2014 07.jpg", 'center 30%'),
  emissions_jeunesse_cultes: cover("Dorothée 1992.jpg", 'center 25%'),
  dessins_animes_90s_2000s: cover("S.B.S.P.jpg", 'center 34%'),
  disney_renaissance: cover("Beauty and the Beast Live on Stage at Disney's Hollywood Studios in Orlando, FL.jpg", 'center 30%'),
  sagas_fantastiques: cover("Lord of the Rings cosplay at Fan Expo Denver 2026 02.jpg", 'center 28%'),
  sherlock_holmes_enquetes: cover("Statue of Sherlock Holmes, London, 2015-04-13.jpg", 'center 28%'),
  series_policieres: cover("NCIS cast members at Miramar (cropped).jpg", 'center 27%'),
  series_medicales: cover("Ellen Pompeo LF.JPG", 'center 24%'),
};

export function getTopicCover(category) {
  // Existing covers were already selected for the exact quiz and validated
  // in production. A new editorial candidate must never silently replace
  // an obvious subject such as Booba, Nadal or a league-specific montage.
  if (category.cover) {
    return {
      src: category.cover,
      source: null,
      focal: category.coverFocal || 'center 25%',
    };
  }

  if (TOPIC_COVERS[category.key]) return TOPIC_COVERS[category.key];

  // Never pretend a generic family photo represents a specific quiz.
  // Uncurated topics keep their original graphic tile until a reviewed,
  // category-specific image is available.
  return null;
}
