const commonsFile = (name) =>
  `https://commons.wikimedia.org/wiki/Special:Redirect/file/${encodeURIComponent(name)}?width=960`;

const commonsPage = (name) =>
  `https://commons.wikimedia.org/wiki/File:${encodeURIComponent(name)}`;

const cover = (file, focal = 'center 35%') => ({
  src: commonsFile(file),
  source: commonsPage(file),
  focal,
});

const remoteCover = (src, source, focal = 'center 30%') => ({ src, source, focal });

export const FAMILY_TOPIC_COVERS = {
  entertainment: cover('Debrie Parvo 35mm Movie Camera.jpg', 'center 48%'),
  music: cover('BBC Proms 31.jpg', 'center 46%'),
  sport: cover('4 sports photo.jpg', 'center 42%'),
  culture: cover('OrteliusWorldMap.jpeg', 'center 42%'),
  gaming: cover('ArcadeGames.jpg', 'center 45%'),
};

// Every entry is reviewed for immediate topic recognition at thumbnail size.
// Unreviewed categories intentionally keep their graphic tile instead of
// receiving a misleading generic family photograph.
export const TOPIC_COVERS = {
  movies: cover('Debrie Parvo 35mm Movie Camera.jpg', 'center 48%'),
  music: cover('BBC Proms 31.jpg', 'center 46%'),
  sports: cover('4 sports photo.jpg', 'center 42%'),
  geography: cover('OrteliusWorldMap.jpeg', 'center 42%'),
  gaming: cover('ArcadeGames.jpg', 'center 45%'),
  science: cover('Laboratory.jpg', 'center 38%'),
  rap_fr: cover("IAM à l'Olympia de Montréal.jpg", 'center 30%'),
  foot_fr: cover('Kylian Mbappe - France v Norway - 26 June 2026 (cropped).jpg', 'center 24%'),
  cinema_fr: cover('Famous French Actors.jpg', 'center 32%'),
  culture_fr: cover('Mont Saint-Michel France.jpg', 'center 42%'),
  premier_league: cover("Premier League Trophy at Manchester's National Football Museum (Ank Kumar) 01.jpg", 'center 30%'),
  la_liga: cover('Lamine Yamal France v Spain 7.24.26-187.jpg', 'center 24%'),
  ligue_1: cover("Paris Saint-Germain - Olympique de Marseille, 8 février 2026 (292).jpg", 'center 34%'),
  serie_a: cover("2009-08 Derby- AC Milan vs Inter at San Siro.jpg", 'center 42%'),
  netflix: cover("Netflix 2016 N logo.svg", 'center 48%'),
  seconde_guerre_mondiale: cover('WW2Montage.PNG', 'center 42%'),
  fortnite: cover('Fortnite cosplay at E3 2018.jpg', 'center 25%'),
  lionel_messi: cover('Lionel Messi WC2022.jpg', 'center 22%'),
  bandes_originales_de_films: cover("Hans Zimmer live.jpg", 'center 30%'),
  culture_manga: cover("Bookshelves with manga.jpg", 'center 44%'),
  films_pixar: cover("Cosplay of Woody from Toy Story at Brussels Comic Con 2022 (51970889736).jpg", 'center 30%'),
  mythologie_grecque: cover('Zeus Otricoli Pio-Clementino Inv257.jpg', 'center 25%'),
  mythologie_egyptienne: cover('Egypt Abou Simbel3.jpg', 'center 42%'),
  films_musicaux: cover('Gentlemen Prefer Blondes Movie Trailer Screenshot (34).jpg', 'center 25%'),
  legendes_de_l_esport: cover('Caps 2025.jpg', 'center 24%'),
  cyclisme_stars: cover("Tadej Pogacar wearing yellow jersey of Tour de France 2025 in stage 14.jpg", 'center 30%'),
  got: cover('GoT at Design Exchange IMG 8710 (8564745129).jpg', 'center 36%'),
  harry_potter: cover('Wizarding World of Harry Potter Castle.jpg', 'center 44%'),
  marvel: cover("NYCC 2019 Cosplay of the Avengers 01.jpg", 'center 38%'),
  star_wars: cover('NYCC 2023 Cosplay of Darth Vader.jpg', 'center 24%'),
  disney: cover('SleepingBeautyCastle.JPG', 'center 42%'),
  pokemon: cover('Pikachu Parade (14905092432).jpg', 'center 34%'),
  f1: cover('Lewis Hamilton during Hungarian Formula 1 GP.jpg', 'center 24%'),
  nba: cover('LeBron James (31944491583).jpg', 'center 28%'),
  tv_shows: cover('Central Perk set.jpg', 'center 46%'),
  histoire_fr: cover('Eugène Delacroix - La liberté guidant le peuple - après restauration 2024.jpg', 'center 36%'),
  retro_games: cover('NES-Console-Set.jpg', 'center 48%'),
  espace_astronomie: cover('Pillars of Creation.jpeg', 'center 42%'),
  corps_humain: cover('Human Anatomy (NIH BioArt 519 - 657946).png', 'center 42%'),
  ligue_champions: cover('Champions League Trophy (52736201132).jpg', 'center 38%'),
  coupe_du_monde_histoire: cover('Kylian Mbappé World Cup Trophy.jpg', 'center 25%'),
  tour_de_france: cover('UAE Team, Tadej Pogačar - Yellow jersey peloton with crowd in Peyresourdes during stage 14 of Tour de France 2025 (cropped).jpg', 'center 30%'),
  jo_ete_histoire: cover('Olympic rings on the Eiffel Tower 2024 (11).jpg', 'center 43%'),
  can_foot_africain: cover('Trophée CAN (1).jpg', 'center 38%'),
  copa_america: cover('Copa america trofeo.jpg', 'center 38%'),
  legendes_foot_allemand_anglais_italien: cover('Cristiano Ronaldo 2018 (4x5 cropped).jpg', 'center 24%'),
  eredivisie: cover('Eredivisie Trophy.png', 'center 42%'),
  drapeaux: cover("UNflags.jpg", 'center 42%'),
  liga_portugal: cover('The 2016-17 Primeira Liga Trophy.jpg', 'center 42%'),
  mls: cover('Lionel Messi NE Revolution Inter Miami 7.9.25-165.jpg', 'center 24%'),
  tennis_atp: cover('Carlos Alcaraz Argentina Open 2024.jpg', 'center 24%'),
  tennis_wta: cover('Iga Swiatek 2023 (cropped).jpg', 'center 24%'),
  roland_garros: cover('Rafael Nadal Roland Garros.jpg', 'center 26%'),
  wimbledon: cover('Wimbledon Centre Court (52205402762).jpg', 'center 42%'),
  rugby_top_14: cover('ST vs RCT 2012 12 Thierry Dusautoir 2.jpg', 'center 28%'),
  mma_ufc: cover('Conor McGregor 2015.jpg', 'center 24%'),
  legendes_du_cyclisme: cover('Eddy Merckx-1973.jpg', 'center 26%'),
  natation_olympique: cover('Michael Phelps conquista 20ª medalha de ouro e é ovacionado 1036417-09082016- mg 6661 01.jpg', 'center 28%'),
  jo_d_hiver_histoire: cover('Cortina d’Ampezzo Olympic Rings 2025 - XXV Giochi olimpici invernali.jpg', 'center 42%'),
  volleyball: cover('Brasil vence a França no vôlei masculino 1037983-15.08.2016 ffz-5559.jpg', 'center 30%'),
  ski_alpin: cover('Lindsey Vonn in Courchevel, 20 december 2015 09.JPG', 'center 25%'),
  sports_d_hiver: cover('Martin Fourcade au tir lors des Jeux Mondiaux Militaires 2013.JPG', 'center 30%'),
  golf: cover('Tiger Woods 20180927.jpg', 'center 25%'),
  nhl: cover('Wgretz edit2.jpg', 'center 25%'),
  baseball_mlb: cover('Shohei Ohtani on April 23, 2024 (2) 53677192000.jpg', 'center 24%'),
  motogp: cover('Valentino Rossi (15131915515).jpg', 'center 25%'),
  rallye_wrc: cover('Sébastien Loeb - 2007 Rally Portugal.jpg', 'center 34%'),
  paris_saint_germain: cover('PSG champion 2015.jpg', 'center 35%'),
  real_madrid: cover("Kylian Mbappe at Real Madrid's game versus Juventus Turin on 22 October 2025.jpeg", 'center 25%'),
  cristiano_ronaldo: cover("Cristiano Ronaldo 0876.jpg", 'center 34%'),
  minecraft: cover('Gamescom 2025 Minecraft.jpg', 'center 38%'),
  gta: cover('Grand-Theft-Auto.png', 'center 45%'),
  league_of_legends: cover('Faker at Worlds 2024.jpg', 'center 24%'),
  valorant: cover('Valorant Champions Tour logo.png', 'center 50%'),
  roblox: cover('Roblox Logo.svg', 'center 50%'),
  call_of_duty: cover("Call of Duty Modern Warfare Gamescom 2019 (48605842367).jpg", 'center 42%'),
  genshin_impact: cover('Cosplay of Raiden Shogun at Made in Asia 2022 (52106490344).jpg', 'center 24%'),
  zelda: cover('Link et Zelda Cosplay.jpg', 'center 25%'),
  univers_mario: cover("Mario and Luigi at Super Nintendo World.jpg", 'center 35%'),
  rugby_coupe_du_monde: cover('RWC 2011 final FRA - NZL McCaw with Ellis Cup.jpg', 'center 30%'),
  xv_de_france: cover('Antoine Dupont February 2023.jpg', 'center 24%'),
  boxe_champions: cover('Muhammad Ali fights Brian London on August 6, 1966 (cropped).jpg', 'center 32%'),
  handball: cover('Nikola Karabatic Team France Handball World Championship 2019 IHF (32931666457).jpg', 'center 27%'),
  nfl: cover('Tom Brady Super Bowl LII 85F9D5D.jpg', 'center 24%'),
  gymnastique: cover('Simone biles 2024 Olympics.jpg', 'center 25%'),
  patinage_artistique: cover('2019 Skate Canada International - Yuzuru Hanyu FS.jpg', 'center 27%'),
  sports_extremes: cover("Tony Hawk skating the Ann Arbor skatepark at Veteran's Memorial Park (cropped).jpg", 'center 35%'),
  femmes_du_sport: cover('SERENA WILLIAMS (3247978825).jpg', 'center 24%'),
  jeunes_talents_du_sport: cover('Lamine Yamal in 2025 (cropped).jpg', 'center 24%'),
  legendes_du_sport_francais: cover('Zinedine zidane wcf 2006.jpg', 'center 25%'),
  padel: cover('Vigo Open 2019 de World Padel Tour - 38.jpg', 'center 36%'),
  beach_volley: cover('Woman beach volley at Paris 2024 olympics France vs Germany 28 07 2024 group stage (cropped).jpg', 'center 32%'),
  k_pop_groupes_feminins: cover('Blackpink Pink Carpet Event 1.jpg', 'center 27%'),
  k_pop_groupes_masculins: cover('190115 BTS at the 2019 Seoul Music Awards.jpg', 'center 28%'),
  bts: cover('BTS in concert at Wembley Stadium, 2 June 2019 01.jpg', 'center 32%'),
  blackpink: cover('Blackpink Pink Carpet Event 3.jpg', 'center 26%'),
  afrobeats: cover('Untold 2024 -Burna Boy (53926047977) (cropped).jpg', 'center 24%'),
  latin_pop_reggaeton: cover('Bad Bunny Performs.jpg', 'center 24%'),
  rap_us_legendes: cover('Eminem performing in 2014 (cropped).jpg', 'center 24%'),
  r_b: cover('Beyonce, I Am... Tour, Bercy 2009.jpg', 'center 24%'),
  variete_francaise: cover('Jean-Jacques Goldman - may 2002.jpg', 'center 25%'),
  chanson_francaise_classique: cover('Edith Piaf Harcourt 1950 2.jpg', 'center 25%'),
  rock_francais: cover('Concert Indochine Arena Tour LDLC Arena - Décines-Charpieu (FR69) - 2025-02-07 - 79.jpg', 'center 28%'),
  rock_legendes_anglo_us: cover('FreddieMercuryNov1977.jpg', 'center 24%'),
  metal: cover('Metallica Warsaw 2024.jpg', 'center 34%'),
  pop_rock_2000s: cover('Avril Lavigne Stage Greatest Hits Tour 2025.jpg', 'center 25%'),
  electro_edm: cover('David Guetta DJing at Ushuaïa Ibiza 2023-07-03 hq.jpg', 'center 25%'),
  house_techno: cover('Daft Punk, 14-6-2007, Bercy, Paris.jpg', 'center 38%'),
  reggae_dancehall: cover('Bob-Marley.jpg', 'center 24%'),
  jazz_legendes: cover('Miles Davis Strasbourg profil bis.jpg', 'center 25%'),
  compositeurs_classiques: cover('Beethoven.jpg', 'center 24%'),
  eurovision: cover('Eurovision 2024 winner Nemo with trophy.jpg', 'center 27%'),
  festivals_de_musique: cover('Coachella main stage at sunset 2004.jpg', 'center 44%'),
  clips_iconiques: cover('Michael Jackson in 1988 (cropped).jpg', 'center 23%'),
  duos_collabs_celebres: cover('Beyoncé and Jay-Z On The Run II.jpg', 'center 29%'),
  comedies_musicales: cover('Stage of the Walter Kerr Theatre with the set of Hadestown.jpg', 'center 45%'),
  girl_groups_boys_bands_2000s_2010s: cover('Spice Girls.jpg', 'center 30%'),
  musique_annees_80: cover('Madonna in concert wearing fishnets 1987 (cropped).jpg', 'center 25%'),
  anime_shonen: cover("Japan Expo 2006 - 2006-07-07 - Cosplay Naruto Luffy.jpg", 'center 30%'),
  studio_ghibli: cover('Ghibli Museum Totoro Stained Glass.jpg', 'center 40%'),
  anime_cultes: cover('Group Portrait of Sailor Moon Cosplayers at CWT41 20151212.jpg', 'center 28%'),
  dc_comics: cover('Cosplay of Batman and Superman at Brussels Comic Con 2022 (51985492234).jpg', 'center 28%'),
  films_dreamworks: cover('Shrek & Fiona.jpg', 'center 26%'),
  comedies_francaises: cover('Louis de Funès 1970.jpg', 'center 24%'),
  comedies_us_cultes: cover('Montreal Comiccon 2016 - The Mask (27999721470).jpg', 'center 24%'),
  films_d_horreur: cover("ExpoSYFY Scream GhostFace mask.jpg", 'center 33%'),
  science_fiction: cover("Astronaut, cosmonaut space suit model in Kennedy Space Center Visitor Complex.jpg", 'center 31%'),
  films_cultes_90s: cover("Quentin Tarantino Uma Thurman John Travolta Cannes 2014.jpg", 'center 29%'),
  films_cultes_2000s: cover("Daniel Radcliffe as Harry Potter.jpg", 'center 24%'),
  oscars_histoire: cover("Ingrid Bergman Holding Oscar.jpg", 'center 27%'),
  cesars: cover("Quentin Tarantino Césars 2011.jpg", 'center 25%'),
  k_pop_rookies_2025_26: cover("Babymonster at Incheon Airport.jpg", 'center 29%'),
  pop_us_montante: cover("Sabrina Carpenter - O2 Arena 2025 - 070 (cropped).jpg", 'center 24%'),
  chappell_roan_pop_alternative: cover("Chappell Roan Sziget 2025.jpg", 'center 25%'),
  rap_us_nouvelle_generation: cover("Travis Scott Circus Maximus Tour Orlando, FL.jpg", 'center 30%'),
  drill_fr_uk: cover("Central cee-5.jpg", 'center 24%'),
  musique_annees_90: cover("Britney Spears 1999.jpg", 'center 25%'),
  musique_annees_2010: cover("Taylor Swift The Eras Tour 1989 Era Set (53109939870) (cropped).jpg", 'center 28%'),
  sons_viraux_tiktok: cover("Charli D'Amelio.jpg", 'center 24%'),
  nouvelle_scene_rap_fr: cover("TiakolaConcert.jpg", 'center 27%'),
  wednesday: cover("Jenna Ortega and Catherine Zeta-Jones 2025 promoting Wednesday.jpg", 'center 26%'),
  stranger_things: cover("Stranger Things cast by Gage Skidmore.jpg", 'center 27%'),
  euphoria: cover("Zendaya 2024 (cropped).jpg", 'center 24%'),
  heartbreak_high: cover("Ayesha Madon for Maybelline Australia & New Zealand 02.jpg", 'center 24%'),
  xo_kitty: cover("Anna Cathcart at WWD Style Awards 2026 (cropped).jpg", 'center 24%'),
  sex_education: cover("Aimee Lou Wood.jpg", 'center 24%'),
  k_dramas: cover("Crash Landing on You cast.jpg", 'center 28%'),
  squid_game: cover("20210923—Lee Jung-jae 이정재, interview, ELLE Taiwan screenshot (02m06s).jpg", 'center 24%'),
  james_bond: cover("Daniel Craig - James Bond (48707836782) (cropped).jpg", 'center 24%'),
  fast_furious: cover("Fast Five Cast.jpg", 'center 29%'),
  films_de_braquage: cover("Affleck09The Town.jpg", 'center 27%'),
  realisateurs_cultes: cover("Steven Spielberg at Berlinale 2023 Ausschnitt.jpg", 'center 25%'),
  acteurs_hollywoodiens_actuels: cover("Timothée Chalamet-63815b.jpg", 'center 24%'),
  actrices_hollywoodiennes_actuelles: cover("Margot Robbie at 29th Critics' Choice Awards.jpg", 'center 24%'),
  stars_du_cinema_coreen: cover("Lee Byung-hun 2025 Toronto (cropped).jpg", 'center 24%'),
  sitcoms_cultes: cover("Friends actors montage.jpg", 'center 33%'),
  tele_realite_fr: cover("Nabilla Benattia 2023 (cropped).jpg", 'center 24%'),
  humoristes_francais: cover("Gad Elmaleh - D'ailleurs.jpg", 'center 26%'),
  stand_up_us: cover("Kevin Hart (15789082350).jpg", 'center 24%'),
  youtubeurs_francais: cover("Squeezie Zack en Roue Libre 2025 (cropped).png", 'center 24%'),
  streamers_twitch_fr: cover("Inoxtag-2023.jpg", 'center 24%'),
  streamers_internationaux: cover("Kai Cenat 2023 (cropped).jpg", 'center 24%'),
  tiktokeurs_celebres: cover("Khaby Lame, Jake from State Farm, and Mat during Tik Tok video shoots (Khaby Lame cropped).jpg", 'center 24%'),
  influenceurs_beaute: cover("James Charles - GLAAD Media Awards 2024 (cropped).png", 'center 24%'),
  createurs_gaming: cover("PewDiePie at PAX 2015.jpg", 'center 24%'),
  celebrites_reseaux_sociaux: cover("MrBeast in 2026 (3x4 cropped).png", 'center 24%'),
  mode_defiles: cover("Paris Fashion Week.jpg", 'center 39%'),
  icones_de_la_mode: cover("Diane von Fürstenberg Spring-Summer 2014 07.jpg", 'center 30%'),
  emissions_jeunesse_cultes: cover("Dorothée 1992.jpg", 'center 25%'),
  dessins_animes_90s_2000s: cover("SpongeBob SquarePants character montage.png", 'center 42%'),
  disney_renaissance: cover("Beauty and the Beast Live on Stage at Disney's Hollywood Studios in Orlando, FL.jpg", 'center 30%'),
  sagas_fantastiques: cover("Bag End, Bilbo Baggins House, Hobbiton Movie Set, Matamata, New Zealand 2016 (50797462102).jpg", 'center 44%'),
  sherlock_holmes_enquetes: cover("Statue of Sherlock Holmes, London, 2015-04-13.jpg", 'center 28%'),
  series_policieres: cover("NCIS cast members at Miramar (cropped).jpg", 'center 27%'),
  series_medicales: cover("Ellen Pompeo LF.JPG", 'center 24%'),
  stars_bollywood: cover("Shah Rukh Khan in 2023 (1).jpg", 'center 24%'),
  cinema_d_auteur_francais: cover("Agnès Varda (Berlinale 2019) (cropped).jpg", 'center 24%'),
  palme_d_or_cannes: cover("Palme d'or.jpg", 'center 38%'),
  acteurs_britanniques: cover("Benedict Cumberbatch-67228.jpg", 'center 24%'),
  comediens_cultes: cover("Robert De Niro Cannes 2016.jpg", 'center 24%'),
  personnages_de_contes_de_fees: cover("Cinderella - Project Gutenberg etext 19993.jpg", 'center 36%'),
  sagas_young_adult: cover("Jennifer Lawrence as Katniss Everdeen (33694624814).jpg", 'center 25%'),
  emissions_de_cuisine: cover("Cooking Show.jpg", 'center 36%'),
  chefs_celebres: cover("Chef Gordon Ramsay.jpg", 'center 24%'),
  top_models: cover("Gigi Hadid in 2019.jpg", 'center 25%'),
  miss_france: cover("Iris Mittenaere 2016.05.07 (cropped).jpg", 'center 24%'),
  culture_meme_internet: cover("Kabosu and Atsuko Sato 2023-11-02 (1).jpg", 'center 40%'),
  comedies_romantiques: cover("Julia Roberts Cannes 2016.jpg", 'center 24%'),
  biopics_celebres: cover("Cillian Murphy at Berlinale 2024-1.jpg", 'center 24%'),
  capitales_du_monde: cover("Paris Eiffel Tower from Trocadero.jpg", 'center 42%'),
  fleuves_montagnes: cover("Mount Everest, Himalayas.jpg", 'center 42%'),
  europe_culture_histoire: cover("Berlaymont EU flags.jpg", 'center 40%'),
  afrique_culture_histoire: cover("Maasai Culture.jpg", 'center 37%'),
  asie_culture_histoire: cover("The Great Wall of China at Jinshanling.jpg", 'center 42%'),
  amerique_latine: cover("Historic Sanctuary of Machu Picchu-109690.jpg", 'center 43%'),
  etats_unis_culture_generale: cover("Statue of Liberty, NY (cropped).jpg", 'center 34%'),
  histoire_antique: cover("Athen's Acropolis at sunset.jpg", 'center 40%'),
  mythologie_nordique: cover("Claes Kurck Skåne hammer - HST DIG55488 original (cropped).jpg", 'center 42%'),
  moyen_age: cover("Knights engage in sword fight during a historical reenactment event in a medieval setting with an audience watching closely.jpg", 'center 34%'),
  premiere_guerre_mondiale: cover("Soldiers in trench.jpg", 'center 36%'),
  revolutions_dans_le_monde: cover("Anonymous - Prise de la Bastille.jpg", 'center 42%'),
  grandes_explorations: cover("Landing of Columbus (2).jpg", 'center 40%'),
  litterature_francaise_classique: cover("Victor Hugo by Étienne Carjat 1876 - full.jpg", 'center 24%'),
  litterature_mondiale: cover("Shakespeare.jpg", 'center 24%'),
  philosophes_celebres: cover("Socrates Louvre.jpg", 'center 28%'),
  peintres_oeuvres_d_art: cover("Mona Lisa, by Leonardo da Vinci, from C2RMF retouched.jpg", 'center 29%'),
  sculpteurs_monuments: cover("Michelangelo's David 2015.jpg", 'center 26%'),
  architecture_celebre: cover("Sagrada Familia 01.jpg", 'center 39%'),
  merveilles_du_monde: cover("All Gizah Pyramids.jpg", 'center 43%'),
  animaux: cover("Lion waiting in Namibia.jpg", 'center 31%'),
  oceans: cover("Coral reef at palmyra.jpg", 'center 42%'),
  dinosaures: cover("FMNH Tyrannosaurus rex Sue.jpg", 'center 37%'),
  environnement_ecologie: cover("The Earth seen from Apollo 17.jpg", 'center 50%'),
  inventions_inventeurs: cover("Thomas Edison2.jpg", 'center 24%'),
  prix_nobel: cover("Nobel prize medal awarded to Alexander Fleming, 1945. (9660573705).jpg", 'center 38%'),
  langues_du_monde: cover("Rosetta Stone.JPG", 'center 40%'),
  traditions_fetes_du_monde: cover("Holi Festival of Colors Utah, United States 2013.jpg", 'center 34%'),
  gastronomie_francaise: cover("Collage French Cuisine by User-EME.png", 'center 42%'),
  gastronomie_du_monde: cover("Gastronomiasdelmundo.jpg", 'center 42%'),
  vins_terroirs: cover("Vineyard in Bordeaux.jpg", 'center 42%'),
  hymnes_nationaux: cover("John Carlos, Tommie Smith, Peter Norman 1968cr.jpg", 'center 32%'),
  femmes_celebres_de_l_histoire: cover("Marie Curie c1920.jpg", 'center 24%'),
  dates_cles_de_l_histoire: cover("History collage.png", 'center 42%'),
  rois_reines_d_europe: cover("Queen Elizabeth II on her Coronation Day (cropped 7-9).jpg", 'center 24%'),
  presidents_francais: cover("Emmanuel Macron portrait (cropped).jpg", 'center 24%'),
  presidents_americains: cover("Mount Rushmore National Memorial 4 Presidents.jpg", 'center 35%'),
  grandes_villes_du_monde: cover("New York City Skyline.jpg", 'center 35%'),
  especes_en_voie_de_disparition: cover("Amur Leopard.jpg", 'center 35%'),
  histoire_du_maroc: cover("Mohammed V.jpg", 'center 25%'),
  histoire_de_l_algerie: cover("EmirAbdelKader.jpg", 'center 35%'),
  histoire_de_la_tunisie: cover("Archaeological Site of Carthage-130237.jpg", 'center 35%'),
  islam: cover("The Kaaba during Hajj - edited.jpg", 'center 35%'),
  christianisme: cover("Saint Peter's Basilica facade, Rome, Italy.jpg", 'center 35%'),
  judaisme: cover("A prayer to God in the Western Wall in Jerusalem.jpg", 'center 35%'),
  bouddhisme: cover("80 Feet Budhdha of Bodh Gaya, Bihar.jpg", 'center 35%'),
  hindouisme: cover("Diwali worship.jpg", 'center 35%'),
  sonic: cover("Sonic Cosplayer at NYCC 2021.jpg", 'center 35%'),
  fifa_ea_sports_fc: cover("Jude Bellingham during an EA Sports event in September 2024.jpg", 'center 35%'),
  assassin_s_creed: cover("Ezio Auditore Cosplay.jpg", 'center 35%'),
  the_witcher: cover("Dragon Con 2025 - Geralt of Rivia cosplay.jpg", 'center 35%'),
  elden_ring: cover("Elden Ring cosplay.jpg", 'center 35%'),
  animal_crossing: cover("WonderCon 2017 - Isabelle (Animal Crossing) cosplay.jpg", 'center 35%'),
  the_sims: cover("Sims cosplay.jpg", 'center 35%'),
  overwatch: cover("Cosplay of D.Va from Overwatch (24760512408).jpg", 'center 35%'),
  counter_strike: cover("Dreamhack Masters Malmö 2017 Stage.jpg", 'center 35%'),
  world_of_warcraft: cover("World of Warcraft cosplayers (16018033652).jpg", 'center 35%'),
  streamers_gaming_fr: cover("Gotaga 2026.jpg", 'center 35%'),
  jeux_mobile_populaires: cover("People playing Pokémon go.jpg", 'center 35%'),
  histoire_des_consoles: cover("The Nostalgia Box - Museum Space.jpg", 'center 35%'),
  fc_barcelone: cover("Messi Barcelona - Valladolid (cropped).jpg", 'center 25%'),
  manchester_united: cover("Manchester United Old Trafford.jpg", 'center 35%'),
  liverpool: cover("Mo Salah 2018 (cropped).jpg", 'center 25%'),
  bayern_munich: cover("Allianz Arena at night, lit in red.JPG", 'center 35%'),
  manchester_city: cover("Erling Haaland 2023 (cropped-v2).jpg", 'center 24%'),
  chelsea: cover("Didier Drogba Champions League Winner 2012.jpg", 'center 25%'),
  arsenal: cover("Arsenal logo at the Emirates Stadium.jpg", 'center 35%'),
  inter_milan: cover("Il biscione e l'fc Internazionale III.jpg", 'center 42%'),
  borussia_dortmund: cover("Suedtribuene.jpg", 'center 45%'),
  olympique_de_marseille: cover("Tifo Virage Sud OM Lille.jpg", 'center 43%'),
  musique_stars: cover("Concert The Weeknd Paris 11.jpg", 'center 35%'),

  // Catalogue expansion batch 1: portraits and official-series posters reviewed at thumbnail size.
  booba: cover("Festival des Vieilles Charrues 2019 - Booba - 038.jpg", 'center 24%'),
  jul: cover("JUL - Julien Mari 2018.jpg", 'center 24%'),
  pnl: cover("PNL (Peace N’ Lovés) '16 concert.jpg", 'center 24%'),
  ninho: cover("Festival des Vieilles Charrues 2022 - Ninho - 041.jpg", 'center 24%'),
  sch: cover("Festival des Vieilles Charrues 2022 - SCH - 038 (cropped).jpg", 'center 24%'),
  damso: cover("Festival des Vieilles Charrues 2018 - Damso - 053.jpg", 'center 24%'),
  orelsan: cover("Orelsan Deauville 2019.jpg", 'center 24%'),
  gims: cover("NDLE2025Gims 1.jpg", 'center 24%'),
  aya_nakamura: cover("Aya Nakamura IMG 4756 (cropped).jpg", 'center 24%'),
  nekfeu: cover("Nekfeu avp.jpg", 'center 24%'),
  gazo: cover("P2N2023Gazo 2.jpg", 'center 24%'),
  tiakola: cover("TiakolaConcert.jpg", 'center 24%'),
  lomepal: cover("Festival des Vieilles Charrues 2019 - Lomepal - 038.jpg", 'center 24%'),
  soprano: cover("Portrait de Soprano lors du festival des Alpagas bleus à Saverne en 2026.jpg", 'center 24%'),
  drake: cover("Drake July 2016.jpg", 'center 24%'),
  eminem: cover("Eminem 2021 Color Corrected.jpg", 'center 24%'),
  kanye_west: cover("Kanye West at the Met Gala in 2019.png", 'center 24%'),
  travis_scott: cover("TravisScott-byPhilipRomano.jpg", 'center 24%'),
  the_weeknd: cover("The Weeknd Portrait by Brian Ziff.jpg", 'center 24%'),
  rihanna: cover("Rihanna Fenty 2018.png", 'center 24%'),
  beyonce: cover("Beyoncé - Tottenham Hotspur Stadium - 1st June 2023 (10 of 118) (52946364598) (best crop).jpg", 'center 24%'),
  taylor_swift: cover("Taylor Swift at the Golden Globes 2024 (Enhanced, cropped) 2.jpg", 'center 24%'),
  michael_jackson: cover("Michael Jackson with Grammy Awards in 1984.jpg", 'center 24%'),
  dua_lipa: cover("Dua Lipa-69798 (cropped).jpg", 'center 24%'),
  billie_eilish: cover("BillieEilishO2140725-39 - 54665577407 (cropped).jpg", 'center 24%'),
  one_piece: remoteCover("https://static.tvmaze.com/uploads/images/original_untouched/504/1262497.jpg", "https://www.tvmaze.com/shows/1505/one-piece", 'center 28%'),
  naruto: remoteCover("https://static.tvmaze.com/uploads/images/original_untouched/3/9744.jpg", "https://www.tvmaze.com/shows/495/naruto", 'center 28%'),
  dragon_ball: remoteCover("https://static.tvmaze.com/uploads/images/original_untouched/11/29190.jpg", "https://www.tvmaze.com/shows/2103/dragon-ball-z", 'center 28%'),
  demon_slayer: remoteCover("https://static.tvmaze.com/uploads/images/original_untouched/456/1140750.jpg", "https://www.tvmaze.com/shows/41469/demon-slayer", 'center 28%'),
  jujutsu_kaisen: remoteCover("https://static.tvmaze.com/uploads/images/original_untouched/608/1521905.jpg", "https://www.tvmaze.com/shows/48450/jujutsu-kaisen", 'center 28%'),
  attaque_des_titans: remoteCover("https://static.tvmaze.com/uploads/images/original_untouched/632/1582290.jpg", "https://www.tvmaze.com/shows/919/attack-on-titan", 'center 28%'),
  hunter_x_hunter: remoteCover("https://static.tvmaze.com/uploads/images/original_untouched/223/559165.jpg", "https://www.tvmaze.com/shows/1536/hunter-x-hunter", 'center 28%'),
  my_hero_academia: remoteCover("https://static.tvmaze.com/uploads/images/original_untouched/599/1499141.jpg", "https://www.tvmaze.com/shows/13615/my-hero-academia", 'center 28%'),
  death_note: remoteCover("https://static.tvmaze.com/uploads/images/original_untouched/499/1249019.jpg", "https://www.tvmaze.com/shows/40/death-note", 'center 28%'),
  breaking_bad: remoteCover("https://static.tvmaze.com/uploads/images/original_untouched/501/1253519.jpg", "https://www.tvmaze.com/shows/169/breaking-bad", 'center 28%'),
  the_walking_dead: remoteCover("https://static.tvmaze.com/uploads/images/original_untouched/424/1061900.jpg", "https://www.tvmaze.com/shows/73/the-walking-dead", 'center 28%'),
  la_casa_de_papel: remoteCover("https://static.tvmaze.com/uploads/images/original_untouched/376/940830.jpg", "https://www.tvmaze.com/shows/27436/la-casa-de-papel", 'center 28%'),
  peaky_blinders: remoteCover("https://static.tvmaze.com/uploads/images/original_untouched/48/122213.jpg", "https://www.tvmaze.com/shows/269/peaky-blinders", 'center 28%'),
  the_boys: remoteCover("https://static.tvmaze.com/uploads/images/original_untouched/169/424458.jpg", "https://www.tvmaze.com/shows/15299/the-boys", 'center 28%'),
  the_last_of_us_serie: remoteCover("https://static.tvmaze.com/uploads/images/original_untouched/563/1409008.jpg", "https://www.tvmaze.com/shows/46562/the-last-of-us", 'center 28%'),
  house_of_the_dragon: remoteCover("https://static.tvmaze.com/uploads/images/original_untouched/627/1568449.jpg", "https://www.tvmaze.com/shows/44778/house-of-the-dragon", 'center 28%'),
  friends: remoteCover("https://static.tvmaze.com/uploads/images/original_untouched/41/104565.jpg", "https://www.tvmaze.com/shows/431/friends", 'center 28%'),
  the_office: remoteCover("https://static.tvmaze.com/uploads/images/original_untouched/481/1204342.jpg", "https://www.tvmaze.com/shows/526/the-office", 'center 32%'),
  vikings: remoteCover("https://static.tvmaze.com/uploads/images/original_untouched/286/715906.jpg", "https://www.tvmaze.com/shows/29/vikings", 'center 28%'),
  prison_break: remoteCover("https://static.tvmaze.com/uploads/images/original_untouched/104/261034.jpg", "https://www.tvmaze.com/shows/541/prison-break", 'center 28%'),
  black_mirror: remoteCover("https://static.tvmaze.com/uploads/images/original_untouched/564/1411764.jpg", "https://www.tvmaze.com/shows/305/black-mirror", 'center 28%'),
  les_simpson: remoteCover("https://static.tvmaze.com/uploads/images/original_untouched/637/1594614.jpg", "https://www.tvmaze.com/shows/83/the-simpsons", 'center 28%'),
  south_park: remoteCover("https://static.tvmaze.com/uploads/images/original_untouched/43/108946.jpg", "https://www.tvmaze.com/shows/112/south-park", 'center 28%'),
  avatar_le_dernier_maitre_de_l_air: remoteCover("https://static.tvmaze.com/uploads/images/original_untouched/79/199224.jpg", "https://www.tvmaze.com/shows/555/avatar-the-last-airbender", 'center 28%'),
  bob_l_eponge: remoteCover("https://static.tvmaze.com/uploads/images/original_untouched/594/1486607.jpg", "https://www.tvmaze.com/shows/713/spongebob-squarepants", 'center 28%'),
};

export function getTopicCover(category) {
  // Existing covers were already selected for the exact quiz and validated
  // in production. A new editorial candidate must never silently replace
  // an obvious subject such as Booba, Nadal or a league-specific montage.
  if (category.cover) {
    return {
      src: category.cover,
      source: null,
      focal: category.coverFocal || 'center 25%',
    };
  }

  if (TOPIC_COVERS[category.key]) return TOPIC_COVERS[category.key];

  // Never pretend a generic family photo represents a specific quiz.
  // Uncurated topics keep their original graphic tile until a reviewed,
  // category-specific image is available.
  return null;
}
